language: ruby
rvm:
- 2.2
- 1.9.3
env:
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=debian:8 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:12.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=ubuntu:16.04 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:20 ANSIBLE_VERSIONS=2.1.0.0
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.4.4
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.6.1
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=1.8.4
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.0.0.2
- DOCKER_IMAGES=fedora:24 ANSIBLE_VERSIONS=2.1.0.0
sudo: false
services:
- docker
script:
- wget -O- bit.ly/ansibletest | sh -x
after_failure:
- cat role-tester-ansible-master/.kitchen/logs/*.log | grep -v '^I, '
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    on_success: change
    on_failure: change
    rooms:
    - secure: 5eVjwNz41WkV512ZqWiTw4mVtCFqwzX1RF0qtyOgx/ckSHsBuA10rIkDccUB8MjOpt+McIGQ7FhpdyYh5eLej7Mog4pvH0Wud4wrMNnCWg1bRORKpZ8irNTz9gV1NKvManoxFmpYnzfRE5I03WhbOPIOZqD2k+K+NGfaRVFV6AgOjfhqtZvvhYgbJP68wh+keR7Yx//xeqivm58HgBpwPD91EMlTrSd+AxoITgHI7pcCW3cmPhNgyenjIjA6H2S4Y8y+bvEtzpNcFswdHMUPzRlsBl4Jr6x3qAAUUT6xPVumU5oaHTdZCYFVqjaI0NOWQvPxERbNA0pdldwIUBpuZy2MvwkjgSpgOFHAf0xyPMP8Cr9NmnqofzTeXrVq1OHqXrwZJ/EtuVivjvkRKqusePAm1UnfXRRCY7BRc8zG4O0asmhYITek35J5zRxZxKolO7IjY5rBKopYC39ZK0m0RIs0H9yIDhHf8uBaNpzfvB2RArkZm7y2fDLeive2nFtAIxEEmo/OUMtjhzEF/UeQw5oVNX0OGo5jgmixouJ0FRrFLZEckkqnANXkRm5wFMCotNvQ7xO2KFjQcSZJpcQtzFCcfktmoXivig7Mk62KDhmgbS9l/m8Og2TVecJx+ukUs0o7eth+dzOL0kD6Ns+RW6JXaRGw8gr+Ej1dZcueWT0=
  email:
    recipients:
      secure: EGNY08GYXLjSMINDfEBqu5ZknlB9l3hs/l4y3Zmo2HBq2WezzI8BFYcTAKc4qgJWoSCC7JAzQZEre7yfrR3bzKqcmsvxO8p90QcBiI/CJJgm2FSKwcRqiENBjN1ZBDswWE8zKY3cjRtqAUqpzRKv4SjfseyFcoP48+Li9FcYvJsq6KO5i+eTPrKB9G/2MYeKmLRTUYYhmknmFNN4PN1GoraKJcJP0rmTZo+tD6bZGQpNrs0J+7n0qgQkzv1bbRzv6WngRueCEC7DEpPctXaQnujHKzeaLpFSuuPPa7+ippM+qmrYxk7y8VRUwfeHNAZppInHAZXmxpUmmojK0OlV+4yZjLtI29szS0a3/ycD4lvP5m6hIk6mSMoVR7DQHF1zpBaCpi3KZhFBbk2Wv2tVyNEhFRDreAzeRn20F/ANgDk9nYxgUIe56UZXGr/TaZo+1dt7rQsrxdoOiMGN5WLHty8g8mh7WFAKvNO7Y3HRgCVI5cgrQ1l9tL9l9XbzTbhZIEGVMzvluxX+ubpcnRZFF5DZuxNWaSufgJtWyPuL+jjTrwDi/maP/8gsCQPoP8MRjJw13fypg7qFU81oNVWN4N46iFoBBO083ybn1LgUykkBg48Lt9v59/jjlreJZxhG+CM++nTV09Htnq4566/Y/C9z21hWLvDZ8qSpsj6D+dU=
