---
- name: apt-get update
  apt: update_cache=true cache_valid_time=3600

- name: add backports repository
  apt_repository: >
    repo="deb http://ftp.debian.org/debian {{ansible_distribution_release}}-backports main"
    state=present
    update_cache=yes
  register: backports_result
  when: should_run and ansible_distribution == 'Debian'

# Download keys and package lists
- name: apt-get update
  apt: update_cache=yes cache_valid_time=0
  when: should_run and backports_result.changed
